spring.application.name=meeting-scheduler-api-java

spring.datasource.url=jdbc:postgresql://localhost:3002/scheduler
spring.datasource.username=scheduler
spring.datasource.password=scheduler

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info